name: "z Slack notify"

on:
  pull_request:
    branches:
      - main 
    type:
      - closed
  workflow_dispatch:

jobs:
  notify:
    name: Slack notify
    runs-on: ubuntu-latest
    steps:
      - name: Slack notify
        uses: slackapi/slack-github-action@v1.24.0
        with:
          channel-id: "C05BZPW2LDP"
          payload: |
            {
              "attachments": [
                {
                  "color": "#0068B7",
                  "blocks": [
                    {
                      "type": "header",
                      "text": {
                        "type": "plain_text",
                        "text": "プルリク結果の通知です！！",
                        "emoji": true
                      }
                    },
                    {
                      "type": "section",
                      "text": {
                        "type": "mrkdwn",
                        "text": "`mainブランチに正常にマージされました！`\n <${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }} | Github Actions>"
                      }
                    }
                  ]
                }
              ]
            }
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}